"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";

type Upload = { coverUrl: string; coverKey: string; coverName: string; coverMimeType: string; coverByteSize: number };
type Form = { title: string; slug: string; type: string; category: string; excerpt: string; body: string; status: string; featured: boolean } & Partial<Upload>;

export default function EditContentPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const [form, setForm] = useState<Form | null>(null);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [assetCount, setAssetCount] = useState(0);

  useEffect(() => { void fetch(`/api/admin/content/${id}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setAssetCount(data.item.assets?.length || 0); setForm({ title: data.item.title, slug: data.item.slug, type: data.item.type, category: data.item.category || "", excerpt: data.item.excerpt || "", body: data.item.body || "", status: data.item.status, featured: data.item.featured }); }).catch((reason) => setError(reason.message)); }, [id]);
  const update = (key: keyof Form, value: string | boolean | number) => setForm((current) => current ? { ...current, [key]: value } : current);
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setError(""); setUploading(true); const data = new FormData(); data.append("file", file); data.append("type", "content"); const response = await fetch("/api/admin/upload", { method: "POST", body: data }); const result = await response.json(); setUploading(false); if (!response.ok) return setError(result.error || "Upload failed"); setForm((current) => current ? { ...current, coverUrl: result.url, coverKey: result.fileName, coverName: result.originalName, coverMimeType: result.mimeType, coverByteSize: result.byteSize } : current); }
  async function save(event: React.FormEvent) { event.preventDefault(); if (!form) return; setSaving(true); setError(""); const response = await fetch(`/api/admin/content/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setSaving(false); if (!response.ok) { const data = await response.json(); return setError(data.error || "Save failed"); } router.push("/admin/content"); }
  if (error && !form) return <p className="p-8 text-red-700">{error}</p>;
  if (!form) return <p className="p-8 text-gray-500">Loading...</p>;
  return <main className="min-h-screen bg-gray-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-4xl justify-between px-6 py-5"><h1 className="text-xl font-bold">Edit content</h1><Link href="/admin/content" className="text-sm text-gray-600">Back to library</Link></div></header><form onSubmit={save} className="mx-auto max-w-4xl space-y-6 px-6 py-8"><section className="rounded-lg bg-white p-7 shadow-sm"><label className="mb-2 block text-sm font-medium">Title</label><input required value={form.title} onChange={(event) => update("title", event.target.value)} className="mb-5 w-full rounded border px-3 py-2" /><div className="grid gap-5 md:grid-cols-2"><input required value={form.slug} onChange={(event) => update("slug", event.target.value)} className="w-full rounded border px-3 py-2" /><select value={form.type} onChange={(event) => update("type", event.target.value)} className="w-full rounded border px-3 py-2">{["GUIDE", "INSPIRATION", "JOURNAL", "CASE_STUDY", "LOOKBOOK", "DOWNLOAD"].map((type) => <option key={type}>{type}</option>)}</select></div></section><section className="rounded-lg bg-white p-7 shadow-sm"><textarea value={form.excerpt} onChange={(event) => update("excerpt", event.target.value)} rows={3} className="mb-5 w-full rounded border px-3 py-2" placeholder="Excerpt" /><textarea value={form.body} onChange={(event) => update("body", event.target.value)} rows={14} className="w-full rounded border px-3 py-2 font-mono text-sm" placeholder="Body" /></section><section className="rounded-lg bg-white p-7 shadow-sm"><label className="mb-2 block text-sm font-medium">Add PDF or image</label><input type="file" accept="image/*,.pdf" onChange={upload} disabled={uploading} className="block text-sm" /><p className="mt-2 text-xs text-gray-500">{form.coverName ? `Ready to attach: ${form.coverName}` : `${assetCount} file${assetCount === 1 ? "" : "s"} already attached`}</p><input value={form.category} onChange={(event) => update("category", event.target.value)} className="mt-5 w-full rounded border px-3 py-2" placeholder="Category" /><div className="mt-5 flex gap-6 text-sm"><label><input type="checkbox" checked={form.featured} onChange={(event) => update("featured", event.target.checked)} /> Featured</label><label>Status <select value={form.status} onChange={(event) => update("status", event.target.value)} className="ml-2 rounded border px-2 py-1"><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label></div></section>{error && <p className="text-sm text-red-700">{error}</p>}<button disabled={saving || uploading} className="rounded bg-[#19382f] px-6 py-3 text-sm font-semibold text-white disabled:opacity-50">{uploading ? "Uploading..." : saving ? "Saving..." : "Save changes"}</button></form></main>;
}
