import { promises as fs } from "node:fs";
import path from "node:path";
import { NextResponse } from "next/server";
import { getProducts, type Product } from "@/data/products";
import { isAdmin } from "@/lib/admin-auth";
const file = path.join(process.cwd(), "data/products.json");
function validProduct(value: unknown): value is Product { if (!value || typeof value !== "object") return false; const p = value as Record<string, unknown>; return typeof p.handle === "string" && /^[a-z0-9-]+$/.test(p.handle) && typeof p.title === "string" && p.title.length > 0 && typeof p.price === "number" && Number.isFinite(p.price) && p.price >= 0 && typeof p.image === "string" && typeof p.description === "string" && Array.isArray(p.features) && Array.isArray(p.spaces) && ["solar", "portable", "privacy"].includes(String(p.collection)); }
export async function GET() { if (!(await isAdmin())) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); return NextResponse.json(getProducts()); }
export async function POST(request: Request) { if (!(await isAdmin())) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const product = await request.json().catch(() => null); if (!validProduct(product)) return NextResponse.json({ error: "Invalid product." }, { status: 400 }); const products = getProducts(); if (products.some((item) => item.handle === product.handle)) return NextResponse.json({ error: "Handle already exists." }, { status: 409 }); products.push(product); await fs.writeFile(file, `${JSON.stringify(products, null, 2)}\n`); return NextResponse.json(product, { status: 201 }); }
export async function PUT(request: Request) { if (!(await isAdmin())) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const product = await request.json().catch(() => null); if (!validProduct(product)) return NextResponse.json({ error: "Invalid product." }, { status: 400 }); const products = getProducts(); const index = products.findIndex((item) => item.handle === product.handle); if (index < 0) return NextResponse.json({ error: "Product not found." }, { status: 404 }); products[index] = product; await fs.writeFile(file, `${JSON.stringify(products, null, 2)}\n`); return NextResponse.json(product); }
export async function DELETE(request: Request) { if (!(await isAdmin())) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const handle = new URL(request.url).searchParams.get("handle"); const products = getProducts(); const next = products.filter((item) => item.handle !== handle); if (next.length === products.length) return NextResponse.json({ error: "Product not found." }, { status: 404 }); await fs.writeFile(file, `${JSON.stringify(next, null, 2)}\n`); return NextResponse.json({ ok: true }); }
