"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

export default function NewContentPage() {
  const router = useRouter();
  const [form, setForm] = useState({ title: "", slug: "", type: "GUIDE", category: "", excerpt: "", body: "", status: "DRAFT", featured: false, coverUrl: "" });
  const [saving, setSaving] = useState(false);
  const update = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const data = new FormData(); data.append("file", file); data.append("type", "content"); const response = await fetch("/api/admin/upload", { method: "POST", body: data }); const result = await response.json(); if (!response.ok) return alert(result.error || "Upload failed"); update("coverUrl", result.url); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); const response = await fetch("/api/admin/content", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setSaving(false); if (!response.ok) { const result = await response.json(); return alert(result.error || "Save failed"); } router.push("/admin/content"); };
  return <main className="min-h-screen bg-gray-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-5"><h1 className="text-xl font-bold text-gray-900">New content</h1><Link href="/admin/content" className="text-sm text-gray-600">Back to library</Link></div></header><form onSubmit={submit} className="mx-auto max-w-4xl space-y-6 px-6 py-8"><section className="rounded-lg bg-white p-7 shadow-sm"><label className="mb-2 block text-sm font-medium">Title *</label><input required value={form.title} onChange={(e) => update("title", e.target.value)} className="mb-5 w-full rounded border px-3 py-2" /><div className="grid gap-5 md:grid-cols-2"><div><label className="mb-2 block text-sm font-medium">Slug *</label><input required value={form.slug} onChange={(e) => update("slug", e.target.value)} className="w-full rounded border px-3 py-2" placeholder="images-of-garden-lights" /></div><div><label className="mb-2 block text-sm font-medium">Type</label><select value={form.type} onChange={(e) => update("type", e.target.value)} className="w-full rounded border px-3 py-2">{["GUIDE", "INSPIRATION", "JOURNAL", "CASE_STUDY", "LOOKBOOK", "DOWNLOAD"].map((type) => <option key={type}>{type}</option>)}</select></div></div></section><section className="rounded-lg bg-white p-7 shadow-sm"><label className="mb-2 block text-sm font-medium">Excerpt</label><textarea value={form.excerpt} onChange={(e) => update("excerpt", e.target.value)} rows={3} className="mb-5 w-full rounded border px-3 py-2" /><label className="mb-2 block text-sm font-medium">Body</label><textarea value={form.body} onChange={(e) => update("body", e.target.value)} rows={12} className="w-full rounded border px-3 py-2 font-mono text-sm" /></section><section className="rounded-lg bg-white p-7 shadow-sm"><label className="mb-2 block text-sm font-medium">Cover image or PDF</label><input type="file" accept="image/*,.pdf" onChange={upload} className="block text-sm" />{form.coverUrl && <p className="mt-2 truncate text-xs text-green-700">Uploaded: {form.coverUrl}</p>}<div className="mt-5 flex flex-wrap gap-6"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.featured} onChange={(e) => update("featured", e.target.checked)} /> Featured on homepage</label><label className="flex items-center gap-2 text-sm">Status <select value={form.status} onChange={(e) => update("status", e.target.value)} className="rounded border px-2 py-1"><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label></div></section><button disabled={saving} className="rounded bg-[#19382f] px-6 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving..." : "Save content"}</button></form></main>;
}
