// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { findPublishedContent } from "@/lib/content-store";
export const dynamic = "force-dynamic";
function DocumentLinks({ contentId, assetId, url }) { const track = (eventType) => { void fetch("/api/content/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contentId, assetId, eventType, path: window.location.pathname }) }); }; return <div className="w-full"><iframe src={url} title="PDF preview" className="mb-4 h-[520px] w-full border" /><span className="flex gap-4"><a href={url} target="_blank" rel="noreferrer" onClick={() => track("pdf_open")}>Open</a><a href={url} download onClick={() => track("pdf_download")}>Download</a></span></div>; }
export default async function IdeaPage({ params }) { const item = await findPublishedContent((await params).slug); if (!item) notFound(); const images = item.assets.filter((asset) => asset.kind === "IMAGE"); const documents = item.assets.filter((asset) => asset.kind === "DOCUMENT"); return <main className="min-h-screen bg-[#f5f2eb] text-[#19382f]"><header className="mx-auto flex max-w-5xl justify-between px-6 py-7"><Link href="/ideas">All ideas</Link><Link href="/" className="font-[family-name:var(--font-display)] text-2xl">Luma<span className="italic">Yard</span></Link></header><article className="mx-auto max-w-4xl px-6 pb-24 pt-14"><p className="text-xs uppercase tracking-widest text-[#927141]">{item.type}</p><h1 className="mt-5 font-[family-name:var(--font-display)] text-5xl md:text-7xl">{item.title}</h1>{item.excerpt && <p className="mt-6 max-w-2xl text-xl leading-8 text-[#536058]">{item.excerpt}</p>}<div className="prose mt-10 max-w-none">{item.body?.split(/\n\s*\n/).map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div>{images.length > 0 && <div className="mt-12 grid gap-5 sm:grid-cols-2">{images.map((image) => <div key={image.id} className="relative aspect-[4/3] overflow-hidden rounded-t-md"><Image src={image.publicUrl} alt={image.altText || item.title} fill className="object-cover" sizes="50vw" /></div>)}</div>}{documents.length > 0 && <div className="mt-12 space-y-3">{documents.map((doc) => <div key={doc.id} className="flex flex-wrap items-center justify-between gap-4 border border-[#19382f]/20 p-4"><div><p className="text-sm font-semibold">{doc.originalName}</p><p className="text-xs text-[#536058]">{Math.max(1, Math.round(doc.byteSize / 1024))} KB</p></div><DocumentLinks contentId={item.id} assetId={doc.id} url={doc.publicUrl} /></div>)}</div>}</article></main>; }
